# Generated by Django 5.1.6 on 2025-04-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WastePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='waste_images/')),
                ('label', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('material_type', models.CharField(blank=True, max_length=100)),
                ('recyclable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
